<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        body { font-family: DejaVu Sans, sans-serif; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { padding: 8px; border: 1px solid #ddd; }
        th { background-color: #f8f9fa; }
    </style>
</head>
<body>
    <h1>Members Report</h1>
    
    <p>
        Report Date Range: <strong>{{ \Carbon\Carbon::parse($startDate)->format('Y-m-d') }}</strong> to 
        <strong>{{ \Carbon\Carbon::parse($endDate)->format('Y-m-d') }}</strong>
    </p>
    
    <p>Generated by: <strong>ADMIN</strong></p>
    <p>Generated on: <strong>{{ now()->format('Y-m-d H:i:s') }}</strong></p>
    
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Phone</th>
                <th>Email</th>
                <th>Jumuiya</th>
                <th>Status</th>
                <th>Joined Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $index => $member)

            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $member->user->name }}</td>
                <td>{{ $member->phone }}</td>
                <td>{{ $member->user->email }}</td>
                <td>{{ $member->jumuiya->name }}</td>
                <td>{{ ucfirst($member->status) }}</td>
                <td>{{ $member->created_at->format('Y-m-d') }}</td>
            </tr>
            @endforeach

            @if($data->isEmpty())
            <tr>
                <td colspan="7" style="text-align:center;">No members found for the selected date range.</td>
            </tr>
            @endif
        </tbody>
    </table>
</body>
</html>
